# Generated by Django 2.2.1 on 2020-06-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchschedule',
            name='end_time',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='matchschedule',
            name='start_time',
            field=models.CharField(max_length=24),
        ),
    ]
